# Generated by Django 4.2.11 on 2024-05-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_payment_razorpayorder"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RazorpayOrder",
            new_name="RazorpayCreateOrder",
        ),
    ]
