# Generated by Django 4.2.11 on 2024-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_rename_razorpayorder_razorpaycreateorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="razorpaycreateorder",
            name="order_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
