# Generated by Django 4.2.13 on 2024-05-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_razorpaycreateorder_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="currency",
        ),
    ]
