# Generated by Django 4.2.13 on 2024-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_remove_payment_amount_remove_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default="", max_digits=20),
        ),
        migrations.AlterField(
            model_name="razorpaycreateorder",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
