# Generated by Django 4.2.13 on 2024-05-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_alter_payment_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
    ]
