# Generated by Django 4.2.13 on 2024-05-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_remove_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razorpaycreateorder",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
    ]
