# Generated by Django 4.2.13 on 2024-05-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0009_alter_razorpaycreateorder_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razorpaycreateorder",
            name="amount",
            field=models.CharField(default="", max_length=100),
        ),
    ]
