# Generated by Django 4.2.13 on 2024-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0010_alter_razorpaycreateorder_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razorpaycreateorder",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
